<a href="https://colab.research.google.com/github/saktiworkstation/road-to-ai-developer/blob/main/Tensor_Operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

# Block 1: Creating Tensors

In [3]:
# a scalar tensor
scalar = tf.constant(5)
print("Scalar Tensor:", scalar)

# a 1-D tensor (vector)
vector = tf.constant([1, 2, 3])
print("1-D Tensor (Vector):", vector)

# a 2-D tensor (matrix)
matrix = tf.constant([[1, 2], [3, 4]])
print("2-D Tensor (Matrix):\n", matrix)

# a 3-D tensor
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3-D Tensor:\n", tensor_3d)

Scalar Tensor: tf.Tensor(5, shape=(), dtype=int32)
1-D Tensor (Vector): tf.Tensor([1 2 3], shape=(3,), dtype=int32)
2-D Tensor (Matrix):
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
3-D Tensor:
 tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


# Block 2: Basic Operations

In [4]:
# Addition
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])
add_result = tf.add(a, b)
print("Addition Result:", add_result)

# Subtraction
sub_result = tf.subtract(a, b)
print("Subtraction Result:", sub_result)

# Multiplication
mul_result = tf.multiply(a, b)
print("Multiplication Result:", mul_result)

# Division
div_result = tf.divide(b, a)
print("Division Result:", div_result)

Addition Result: tf.Tensor([5 7 9], shape=(3,), dtype=int32)
Subtraction Result: tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
Multiplication Result: tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
Division Result: tf.Tensor([4.  2.5 2. ], shape=(3,), dtype=float64)


# Block 3: Matrix Operations

In [5]:
# Matrix multiplication
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])
matmul_result = tf.matmul(matrix_a, matrix_b)
print("Matrix Multiplication Result:\n", matmul_result)

# Element-wise multiplication
elem_mul_result = tf.multiply(matrix_a, matrix_b)
print("Element-wise Multiplication Result:\n", elem_mul_result)

Matrix Multiplication Result:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
Element-wise Multiplication Result:
 tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


# Block 4: Tensor Reshaping

In [6]:
# Original tensor
tensor = tf.range(16)
print("Original Tensor:", tensor)

# Reshape to 4x4 matrix
tensor_reshaped = tf.reshape(tensor, [4, 4])
print("Reshaped Tensor (4x4):\n", tensor_reshaped)

# Reshape to 2x2x4 tensor
tensor_reshaped_3d = tf.reshape(tensor, [2, 2, 4])
print("Reshaped Tensor (2x2x4):\n", tensor_reshaped_3d)

Original Tensor: tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15], shape=(16,), dtype=int32)
Reshaped Tensor (4x4):
 tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]], shape=(4, 4), dtype=int32)
Reshaped Tensor (2x2x4):
 tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]], shape=(2, 2, 4), dtype=int32)


# Block 5: Broadcasting

In [7]:
# Broadcasting addition
x = tf.constant([[1], [2], [3]])
y = tf.constant([4, 5, 6])
broadcast_add = x + y
print("Broadcasted Addition Result:\n", broadcast_add)

Broadcasted Addition Result:
 tf.Tensor(
[[5 6 7]
 [6 7 8]
 [7 8 9]], shape=(3, 3), dtype=int32)


# Block 6: Advanced Operations

In [8]:
# Transpose of a matrix
matrix = tf.constant([[1, 2], [3, 4]])
transpose = tf.transpose(matrix)
print("Transpose of Matrix:\n", transpose)

# Inverse of a matrix
matrix_float = tf.constant([[1., 2.], [3., 4.]])
inverse = tf.linalg.inv(matrix_float)
print("Inverse of Matrix:\n", inverse)

# Determinant of a matrix
determinant = tf.linalg.det(matrix_float)
print("Determinant of Matrix:", determinant)

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = tf.linalg.eigh(matrix_float)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Transpose of Matrix:
 tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)
Inverse of Matrix:
 tf.Tensor(
[[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]], shape=(2, 2), dtype=float32)
Determinant of Matrix: tf.Tensor(-2.0, shape=(), dtype=float32)
Eigenvalues: tf.Tensor([-0.8541021  5.854102 ], shape=(2,), dtype=float32)
Eigenvectors:
 tf.Tensor(
[[-0.85065085 -0.5257311 ]
 [ 0.5257311  -0.85065085]], shape=(2, 2), dtype=float32)


# Block 7: Higher-Dimensional Tensors

In [9]:
# Creating a 4-D tensor
tensor_4d = tf.random.uniform([2, 3, 4, 5])
print("Shape of 4-D Tensor:", tensor_4d.shape)

# Sum over specific axes
sum_over_axis = tf.reduce_sum(tensor_4d, axis=2)
print("Sum over axis 2:\n", sum_over_axis)

Shape of 4-D Tensor: (2, 3, 4, 5)
Sum over axis 2:
 tf.Tensor(
[[[2.4225116  2.9752774  1.4205288  0.8543824  1.4694198 ]
  [2.5187643  1.9887627  2.7142015  1.8757874  2.2321577 ]
  [1.8850586  2.0985856  2.1500793  0.68029284 1.8942417 ]]

 [[2.055049   1.6338973  1.1049187  2.2090015  0.8987944 ]
  [2.2628145  1.121169   2.0614243  1.4133867  1.7681371 ]
  [2.5381842  2.7486758  0.9773377  2.7927985  2.2793095 ]]], shape=(2, 3, 5), dtype=float32)


# Block 8: Tensor Operations in Neural Networks

In [10]:
# Dot product
vector_a = tf.constant([1, 2, 3])
vector_b = tf.constant([4, 5, 6])
dot_product = tf.tensordot(vector_a, vector_b, axes=1)
print("Dot Product:", dot_product)

# Batch matrix multiplication
batch_matrix_a = tf.random.uniform([5, 3, 2])
batch_matrix_b = tf.random.uniform([5, 2, 4])
batch_matmul = tf.matmul(batch_matrix_a, batch_matrix_b)
print("Batch Matrix Multiplication Result Shape:", batch_matmul.shape)

Dot Product: tf.Tensor(32, shape=(), dtype=int32)
Batch Matrix Multiplication Result Shape: (5, 3, 4)


# Block 9: Slicing and Indexing

In [11]:
# Creating a tensor
tensor = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slicing
slice_1 = tensor[0, :]  # First row
print("First Row:", slice_1)

slice_2 = tensor[:, 1]  # Second column
print("Second Column:", slice_2)

slice_3 = tensor[1:3, 0:2]  # Sub-matrix
print("Sub-matrix:\n", slice_3)

First Row: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Second Column: tf.Tensor([2 5 8], shape=(3,), dtype=int32)
Sub-matrix:
 tf.Tensor(
[[4 5]
 [7 8]], shape=(2, 2), dtype=int32)


# Block 10: Manipulating Shapes

In [12]:
# Expanding dimensions
tensor = tf.constant([1, 2, 3])
expanded_tensor = tf.expand_dims(tensor, axis=1)
print("Expanded Tensor Shape:", expanded_tensor.shape)

# Squeezing dimensions
tensor_with_extra_dim = tf.constant([[[1], [2], [3]]])
squeezed_tensor = tf.squeeze(tensor_with_extra_dim)
print("Squeezed Tensor Shape:", squeezed_tensor.shape)

Expanded Tensor Shape: (3, 1)
Squeezed Tensor Shape: (3,)


# Block 11: Converting between NumPy and TensorFlow

In [13]:
import numpy as np

# TensorFlow tensor to NumPy array
tensor = tf.constant([1, 2, 3])
numpy_array = tensor.numpy()
print("NumPy Array:", numpy_array)

# NumPy array to TensorFlow tensor
numpy_array = np.array([4, 5, 6])
tensor_from_numpy = tf.constant(numpy_array)
print("Tensor from NumPy:", tensor_from_numpy)

NumPy Array: [1 2 3]
Tensor from NumPy: tf.Tensor([4 5 6], shape=(3,), dtype=int64)


# Block 12: Complex Tensor Operations

In [14]:
# Cholesky decomposition
matrix = tf.constant([[4., 12.], [12., 37.]])
cholesky = tf.linalg.cholesky(matrix)
print("Cholesky Decomposition:\n", cholesky)

# QR decomposition
qr_matrix = tf.constant([[1., 2.], [3., 4.]])
q, r = tf.linalg.qr(qr_matrix)
print("Q Matrix:\n", q)
print("R Matrix:\n", r)

# Singular Value Decomposition (SVD)
svd_matrix = tf.constant([[1., 2., 3.], [4., 5., 6.]])
s, u, v = tf.linalg.svd(svd_matrix)
print("Singular Values:", s)
print("U Matrix:\n", u)
print("V Matrix:\n", v)

Cholesky Decomposition:
 tf.Tensor(
[[2. 0.]
 [6. 1.]], shape=(2, 2), dtype=float32)
Q Matrix:
 tf.Tensor(
[[-0.3162278  -0.9486833 ]
 [-0.9486833   0.31622773]], shape=(2, 2), dtype=float32)
R Matrix:
 tf.Tensor(
[[-3.1622777  -4.4271884 ]
 [ 0.         -0.63245535]], shape=(2, 2), dtype=float32)
Singular Values: tf.Tensor([9.508034   0.77286935], shape=(2,), dtype=float32)
U Matrix:
 tf.Tensor(
[[-0.38631773 -0.92236584]
 [-0.92236584  0.38631773]], shape=(2, 2), dtype=float32)
V Matrix:
 tf.Tensor(
[[-0.42866713  0.8059641 ]
 [-0.56630695  0.1123824 ]
 [-0.70394677 -0.58119917]], shape=(3, 2), dtype=float32)


# Block 13: Tensor Broadcasting with Higher Dimensions

In [15]:
a = tf.constant([[1], [2], [3]])  # Shape (3,1)
b = tf.constant([[1, 2, 3]])      # Shape (1,3)
broadcast_result = a * b          # Shape (3,3)
print("Broadcasted Multiplication Result:\n", broadcast_result)

Broadcasted Multiplication Result:
 tf.Tensor(
[[1 2 3]
 [2 4 6]
 [3 6 9]], shape=(3, 3), dtype=int32)


# Block 14: Conditional Operations

In [16]:
# Where operation
tensor = tf.constant([-1, 2, -3, 4])
positive_tensor = tf.where(tensor > 0, tensor, tf.zeros_like(tensor))
print("Positive Tensor:", positive_tensor)

Positive Tensor: tf.Tensor([0 2 0 4], shape=(4,), dtype=int32)


# Block 15: Random Tensor Generation

In [17]:
# Random normal distribution
random_normal = tf.random.normal([3, 3], mean=0.0, stddev=1.0)
print("Random Normal Tensor:\n", random_normal)

# Random uniform distribution
random_uniform = tf.random.uniform([2, 2], minval=0, maxval=10, dtype=tf.int32)
print("Random Uniform Tensor:\n", random_uniform)

Random Normal Tensor:
 tf.Tensor(
[[-0.40221593  0.19365077 -0.18150443]
 [ 0.7473445   0.35313857 -0.27076334]
 [ 1.5053952  -0.7646306   0.09392023]], shape=(3, 3), dtype=float32)
Random Uniform Tensor:
 tf.Tensor(
[[4 2]
 [6 0]], shape=(2, 2), dtype=int32)
